version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=news_db'
      - 'DATABASE_URI=postgres://localhost:postgres@postgres:5432/news_db?sslmode=disable'
    hostname: 'localhost'
    ports:
      - "5432:5432"

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8081:8081"
    hostname: 'localhost'